name: Coverage report

on:

  push:
    branches: [ master ]


 
jobs:
 
  build:
    runs-on: ubuntu-latest
    steps:
    - name : Setup Flutter    
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.3'

    - name: Flutter Pub get
      run : |
          echo  flutter clean
          echo  flutter pub get
          
    - name : Flutter Analyze
      run  : flutter analyze

    - name : Run Test  
      run  : flutter test

    - name : Run Test Coverage 
      run  : flutter test --coverage

    - name : Install lcov
      run  : sudo apt-get install -y lcov

    # - name : Remove Generated All Generated Files
    #   run  : lcov --remove coverage/lcov.info 'lib/*/*.part.dart' 'lib/generated_plugin_registrant.dart' -o coverage/lcov.info

    - name : Upload Coverage To Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }} 
        files: coverage/lcov.info
